baseURL = "https://Nhantran2004.github.io/My-blog/"
publishDir = "docs"
languageCode = "vi-vn"
title = "Trần Quốc Thành Nhân — Portfolio"

# (Tùy chọn) giúp link tương đối an toàn hơn
relativeURLs = true
canonifyURLs = true

[params]
  # Nếu bạn để file ở static/css/custom.css (khuyên dùng)
  customCSS = ["css/custom.css"]